### ISSUE TITLE
Are you from Sololearn developer team? Just asking?

### ISSUE THREAD

**Issue by Ranjan-Bagri** [iosexample/LearnSwift#1]

**Comment by Ranjan-Bagri** [comment]
Thanks for your precious feedback

**Comment by Ranjan-Bagri** [comment]
Thanks for your precious feedback

**Comment by donly** [comment]
Hi, Ranjan.

I am an iOS developer, but not a member of Sololearn developer team.

Here is [my Sololearn page](https://www.sololearn.com/profile/158678/).

**Comment by Ranjan-Bagri** [comment]
Don, thanks for your precious feedback.
Nice to meet you.
Are you making swift compiler for Sololearn? If yes , does Sololearn know
about it?
